# Generated by Django 3.1.5 on 2021-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210208_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hash',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.CharField(max_length=256),
        ),
    ]
