# Generated by Django 3.1.7 on 2021-03-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210308_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='codename',
            new_name='code1name',
        ),
    ]
