# Generated by Django 3.1.7 on 2021-03-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210308_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code1code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code1name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code2code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code2name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code3code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code3name',
        ),
    ]
